image: alpine

stages:
  - unit_test
  - build_test

before_script:
  - apt update
  - apt upgrade
  - apk add --no-cache python python-dev py-pip build-base git docker
  - pip install docker-compose

unit_test:
  stage: unit_test
  script:
    - docker-compose -f docker-compose-dev.yml up -d --build

build_test:
  stage: build_test
  script:
    - docker-compose -f docker-compose-prod.yml build --no-cache
