image: docker:git

#variables:
  #DOCKER_HOST: tcp://docker:2375
  #DOCKER_DRIVER: overlay

services:
  - docker:dind

stages:
  - unit_test
  - build_test

before_script:
  - apk update
  - apk upgrade
  - apk add --no-cache python python-dev py-pip build-base git openrc docker
  - pip install docker-compose
  - service docker start
  - docker info

unit_test:
  stage: unit_test
  script:
    - docker-compose -f docker-compose-dev.yml up -d --build

build_test:
  stage: build_test
  script:
    - docker-compose -f docker-compose-prod.yml build --no-cache
