version: '3.6'

services:
  front:
    container_name: front
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_AUTH_SERVICE_URL=http://localhost/auth
      - REACT_APP_USERS_SERVICE_URL=http://localhost/users
      - REACT_APP_COMPANIES_SERVICE_URL=http://localhost/companies
      - REACT_APP_SOCIAL_SERVICE_URL=http://localhost/social
      - REACT_APP_NOTIFICATIONS_SERVICE_URL=http://localhost/notifications
      - REACT_APP_EXPORTER_SERVICE_URL=http://localhost/exporter
      - REACT_APP_FACEBOOK_SERVICE_URL=http://localhost/facebook
      - REACT_APP_FACEBOOK_ID=287321418635324
      - REACT_APP_FACEBOOK_VERSION=v3.2
    restart: always
    depends_on:
      - users-service

  users-service:
    container_name: mock-users-service
    build:
      context: ./mockServices/users-service
      dockerfile: Dockerfile
    ports:
      - 5001:80
    restart: always

  users-service-swagger:
    container_name: users-service-swagger
    build:
      context: "https://gitlab+deploy-token-25488:zkcGJFdvCN6KCfmWtnAU@gitlab.com/gusisoft/OneLike/users-service.git#devel:swagger"
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    environment:
      - API_URL=definitions/swagger.yml
    restart: always
    depends_on:
      - users-service
