version: '3.6'

services:
  front:
    container_name: client-front
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
